# docker-compose.yml

version: '3.8'

services:
  blog:
    build:
      context: ./server
    ports:
      - "8001:8001"

  gateway:
    build: ./gateway
    ports:
      - "8000:80"
    depends_on:
    - blog